@echo off

Title Virus!!!!

Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo VIRUS!!!!
Echo Youve been goofed! The virus is just an inconvienience!
pause